#!/bin/bash

set -e

rm -rf ext

# requires: autoconf, libtool, libreadline-dev

mkdir -p ext
cd ext

#zookeeper
FN=zookeeper-3.4.12.tar.gz
FV=zookeeper-3.4.12
wget http://apache.mirrors.tds.net/zookeeper/current/$FN
tar xzf $FN
rm $FN
mv $FV/src/c zookeeper
rm -fr $FV
cd zookeeper
./configure --prefix=$PWD
make -j
cd ..

# protobuf
git clone git@github.com:protocolbuffers/protobuf.git
cd protobuf
git checkout v3.6.1
./autogen.sh
./configure --prefix=$PWD
make -j
cd ..

# googletest
git clone git@github.com:google/googletest.git
cd googletest/googletest
git checkout release-1.6.0
cmake .
make -j
cd ../..

# zeromq
wget http://download.zeromq.org/zeromq-2.1.11.tar.gz
tar xzf zeromq-2.1.11.tar.gz
rm zeromq-2.1.11.tar.gz
mv zeromq-2.1.11 zeromq
cd zeromq
./autogen.sh
mkdir build
cd build
../configure --prefix=$PWD
make -j
make install
cd ../..



